[package]
name = "remindee-bot"
version = "0.1.13"
authors = ["Nikolai Oplachko <magnickolas@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
description = "Reminder bot for Telegram without bullshit"
homepage = "https://oplachko.com"
repository = "https://github.com/magnickolas/remindee-bot"
readme = "README.md"
keywords = ["bot","reminder", "cron", "telegram-bot", "reminders"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.10.0"
chrono = "0.4.19"
chrono-tz = "0.6.0"
cron-parser = "0.7.9"
directories = "4.0.1"
lazy_static = "1.4.0"
regex = "1.5.4"
teloxide = "0.5.3"
teloxide-macros = "0.4.1"
openssl = { version = "0.10.38", features = ["vendored"] }
sea-query = { version = "0.19.0", features = ["sqlx-sqlite", "with-chrono"] }
sqlx = { version = "0.5.9", features = ["runtime-tokio-rustls", "sqlite", "chrono"] }
strum = "0.23.0"
strum_macros = "0.23.1"

log = "0.4.14"
pretty_env_logger = "0.4.0"

tokio = { version = "1.14.0", features = ["rt-multi-thread", "macros"] }
itertools = "0.10.1"
