[package]
name = "remindee-bot"
version = "0.2.0"
authors = ["Nikolai Oplachko <magnickolas@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
description = "Reminder bot for Telegram without bullshit"
homepage = "https://github.com/magnickolas/remindee-bot"
repository = "https://github.com/magnickolas/remindee-bot"
readme = "README.md"
keywords = ["bot", "reminder", "cron", "telegram-bot", "reminders"]
categories = ["command-line-utilities"]

[workspace]
members = ["."]

[dependencies]
async-std = "1.12.0"
async_once = "0.2.6"
chrono = "0.4.23"
chrono-tz = "0.8.1"
cron-parser = "0.7.10"
directories = "4.0.1"
lazy_static = "1.4.0"
log = "0.4.17"
pretty_env_logger = "0.4.0"
regex = "1.7.1"
sea-orm = "0.11.0"

[dependencies.clap]
version = "4.1.4"
features = ["derive", "env", "string"]

[dependencies.sea-orm-migration]
version = "0.11.0"
features = ["runtime-tokio-rustls", "sqlx-sqlite"]

[dependencies.teloxide]
version = "0.12.0"
features = ["macros"]

[dependencies.tokio]
version = "1.25.0"
features = ["rt-multi-thread", "macros"]

[dependencies.openssl]
version = "0.10.45"
features = ["vendored"]

[dev-dependencies]
test-case = "2.2.2"
strfmt = "0.2.3"
