[package]
name = "remindee-bot"
version = "0.1.20"
authors = ["Nikolai Oplachko <magnickolas@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
description = "Reminder bot for Telegram without bullshit"
homepage = "https://oplachko.com"
repository = "https://github.com/magnickolas/remindee-bot"
readme = "README.md"
keywords = ["bot","reminder", "cron", "telegram-bot", "reminders"]
categories = ["command-line-utilities"]

[workspace]
members = [".", "entity", "migration"]

[dependencies]
entity = { path = "./entity", version = "0.1.0" }
migration = { path = "./migration", version = "0.1.0" }
async-std = "1.12.0"
chrono = "0.4.23"
chrono-tz = "0.8.0"
cron-parser = "0.7.10"
directories = "4.0.1"
lazy_static = "1.4.0"
regex = "1.7.0"
teloxide = "0.11.1"
teloxide-macros = "0.7.0"
openssl = { version = "0.10.42", features = ["vendored"] }
async_once = "0.2.6"

log = "0.4.17"
pretty_env_logger = "0.4.0"

tokio = { version = "1.21.2", features = ["rt-multi-thread", "macros"] }
itertools = "0.10.5"

[dev-dependencies]
test-case = "2.2.2"
strfmt = "0.2.2"
