name: CI

on:
  pull_request:
  push:
    paths:
      - .github/workflows/ci.yml
      - Cargo.toml
      - Cargo.lock
      - rustfmt.toml
      - src/**

jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        action:
          - build
          - test
        build: [linux, macos]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
          - build: macos
            os: macos-latest
            rust: stable

    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        run: rustup update stable && rustup default stable && rustup component add rustfmt
      - name: Action
        run: cargo ${{ matrix.action }}

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update stable && rustup default stable && rustup component add rustfmt
      - name: Action
        run: cargo fmt -- --check

  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        run: rustup update stable && rustup default stable && rustup component add rustfmt
      - name: Action
        run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
